# Generated by Django 4.2.5 on 2023-10-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('dataNascimento', models.DateField()),
                ('endereco', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=150)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
    ]
